version: '3.7'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: messages
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/1-init.sql
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    mem_limit: 500m
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
  consumer:
    depends_on: 
        - rabbitmq
        - db
    build: ./consumer
    restart: always
    mem_limit: 500m
  producer:
    depends_on: 
      - rabbitmq
    build: ./producer
    restart: always
    mem_limit: 500m
  
volumes:
  db_data:
  rabbitmq_data:
